don't prevent running on the public repo

diff --git a/.github/workflows/js-uptodate-check.yml b/.github/workflows/js-uptodate-check.yml
--- a/.github/workflows/js-uptodate-check.yml
+++ b/.github/workflows/js-uptodate-check.yml
@@ -11,23 +11,18 @@ jobs:
     - uses: actions/checkout@v1
     - name: Check generated JavaScript
       run: |
-        # Only run if running on private repo
-        if [ "${{ github.event.repository.full_name }}" == "github/codeql-action" ]; then
-          # Sanity check that repo is clean to start with
-          if [ ! -z "$(git status --porcelain)" ]; then
-            # If we get a fail here then this workflow needs attention...
-            >&2 echo "Failed: Repo should be clean before testing!"
-            exit 1
-          fi
-          # Generate the JavaScript files
-          npm run-script build
-          # Check that repo is still clean
-          if [ ! -z "$(git status --porcelain)" ]; then
-            # If we get a fail here then the PR needs attention
-            >&2 echo "Failed: JavaScript files are not up to date. Run 'npm run-script build' to update"
-            exit 1
-          fi
-          echo "Success: JavaScript files are up to date"
-        else
-          echo "This workflow should only run on github/codeql-action"
+        # Sanity check that repo is clean to start with
+        if [ ! -z "$(git status --porcelain)" ]; then
+          # If we get a fail here then this workflow needs attention...
+          >&2 echo "Failed: Repo should be clean before testing!"
+          exit 1
         fi
+        # Generate the JavaScript files
+        npm run-script build
+        # Check that repo is still clean
+        if [ ! -z "$(git status --porcelain)" ]; then
+          # If we get a fail here then the PR needs attention
+          >&2 echo "Failed: JavaScript files are not up to date. Run 'npm run-script build' to update"
+          exit 1
+        fi
+        echo "Success: JavaScript files are up to date"
